# Generated by Django 3.1.5 on 2021-02-01 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='My_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('find', models.CharField(max_length=65)),
                ('replace', models.CharField(max_length=65)),
                ('file', models.FileField(upload_to='')),
                ('path', models.CharField(blank=True, max_length=120, null=True)),
            ],
        ),
    ]
